---
identifier: "CVE-2019-19275"
identifiers:
- "CVE-2019-19275"
- "GHSA-7xxv-wpxj-mx5v"
package_slug: "pypi/typed-ast"
title: "typed-ast Out-of-bounds Read"
description: "typed_ast 1.3.0 and 1.3.1 has an ast_for_arguments out-of-bounds read.
  An attacker with the ability to cause a Python interpreter to parse Python source
  (but not necessarily execute it) may be able to crash the interpreter process. This
  could be a concern, for example, in a web-based service that parses (but does not
  execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)"
date: "2024-11-18"
pubdate: "2019-12-02"
affected_range: ">=1.3.0,<1.3.2"
fixed_versions:
- "1.3.2"
affected_versions: "All versions starting from 1.3.0 before 1.3.2"
not_impacted: "All versions before 1.3.0, all versions starting from 1.3.2"
solution: "Upgrade to version 1.3.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-19275"
- "https://github.com/advisories/GHSA-7xxv-wpxj-mx5v"
- "https://github.com/python/cpython/commit/a4d78362397fc3bced6ea80fbc7b5f4827aec55e"
- "https://github.com/python/cpython/commit/dcfcd146f8e6fc5c2fc16a4c192a0c5f5ca8c53c"
- "https://github.com/python/typed_ast/commit/156afcb26c198e162504a57caddfe0acd9ed7dce"
- "https://github.com/python/typed_ast/commit/dc317ac9cff859aa84eeabe03fb5004982545b3b"
- "https://bugs.python.org/issue36495"
- "https://github.com/pypa/advisory-database/tree/main/vulns/typed-ast/PYSEC-2019-131.yaml"
- "https://github.com/python/typed_ast"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LG5H4Q6LFVRX7SFXLBEJMNQFI4T5SCEA"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "e754a77b-f90f-4249-9726-74a33f5bb768"
cwe_ids:
- "CWE-125"
- "CWE-937"
- "CWE-1035"
