---
identifier: "CVE-2020-24584"
package_slug: "pypi/Django"
title: "Incorrect Default Permissions"
description: "An issue was discovered in Django (when Python + is used). The intermediate-level
  directories of the filesystem cache had the system's standard umask rather than
  `0o077`."
date: "2021-01-20"
pubdate: "2020-09-01"
affected_range: ">=2.2,<2.2.16||>=3.0,<3.0.10||>=3.1,<3.1.1"
fixed_versions:
- "2.2.16"
- "3.0.10"
- "3.1.1"
affected_versions: "All versions starting from 2.2 before 2.2.16, all versions starting
  from 3.0 before 3.0.10, all versions starting from 3.1 before 3.1.1"
not_impacted: "All versions before 2.2, all versions starting from 2.2.16 before 3.0,
  all versions starting from 3.0.10 before 3.1, all versions starting from 3.1.1"
solution: "Upgrade to versions 2.2.16, 3.0.10, 3.1.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2020-24584"
- "https://docs.djangoproject.com/en/dev/releases/security/"
- "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
uuid: "1efdad46-5bb6-4349-a068-fd8d1df03532"
cwe_ids:
- "CWE-1035"
- "CWE-276"
- "CWE-937"
identifiers:
- "CVE-2020-24584"
