---
identifier: "CVE-2024-39614"
identifiers:
- "CVE-2024-39614"
- "GHSA-f6f8-9mx6-9mx2"
package_slug: "pypi/Django"
title: "Django vulnerable to Denial of Service"
description: "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14.
  `get_supported_language_variant()` was subject to a potential denial-of-service
  attack when used with very long strings containing specific characters."
date: "2024-07-10"
pubdate: "2024-07-10"
affected_range: ">=5.0,<5.0.7||>=4.2,<4.2.14"
fixed_versions:
- "5.0.7"
- "4.2.14"
affected_versions: "All versions starting from 4.2 before 4.2.14, all versions starting
  from 5.0 before 5.0.7"
not_impacted: "All versions before 4.2, all versions starting from 4.2.14 before 5.0,
  all versions starting from 5.0.7"
solution: "Upgrade to versions 4.2.14, 5.0.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2024-39614"
- "https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"
- "https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"
- "https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"
- "https://docs.djangoproject.com/en/dev/releases/security"
- "https://github.com/django/django"
- "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"
- "https://groups.google.com/forum/#%21forum/django-announce"
- "https://www.djangoproject.com/weblog/2024/jul/09/security-releases"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "85129dd3-1dbc-4766-8f92-72a4004ea4f0"
cwe_ids:
- "CWE-770"
- "CWE-937"
- "CWE-1035"
