---
identifier: "CVE-2025-61912"
identifiers:
- "CVE-2025-61912"
- "GHSA-p34h-wq7j-h5v6"
package_slug: "pypi/python-ldap"
title: "python-ldap is Vulnerable to Improper Encoding or Escaping of Output and Improper
  Null Termination"
description: "`ldap.dn.escape_dn_chars()` escapes `\\x00` incorrectly by emitting
  a backslash followed by a literal NUL byte instead of the RFC-4514 hex form `\\00`.
  Any application that uses this helper to construct DNs from untrusted input can
  be made to consistently fail before a request is sent to the LDAP server (e.g.,
  AD), resulting in a client-side denial of service."
date: "2025-10-10"
pubdate: "2025-10-10"
affected_range: "<3.4.5"
fixed_versions:
- "3.4.5"
affected_versions: "All versions before 3.4.5"
not_impacted: "All versions starting from 3.4.5"
solution: "Upgrade to version 3.4.5 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-61912"
- "https://github.com/advisories/GHSA-p34h-wq7j-h5v6"
- "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-p34h-wq7j-h5v6"
- "https://github.com/python-ldap/python-ldap/commit/6ea80326a34ee6093219628d7690bced50c49a3f"
- "https://github.com/python-ldap/python-ldap"
- "https://github.com/python-ldap/python-ldap/releases/tag/python-ldap-3.4.5"
uuid: "89053359-6875-42b7-8f4e-e00d389038fb"
cwe_ids:
- "CWE-116"
- "CWE-170"
- "CWE-937"
- "CWE-1035"
