---
identifier: "CVE-2021-29561"
package_slug: "pypi/tensorflow"
title: "Reachable Assertion"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can cause a denial of service by exploiting a `CHECK`-failure coming
  from `tf.raw_ops.LoadAndRemapMatrix`. This is because the implementation assumes
  that the `ckpt_path` is always a valid scalar. However, an attacker can send any
  other tensor as the first argument of `LoadAndRemapMatrix`. This would cause the
  rank `CHECK` in `scalar<T>()()` to trigger and terminate the process."
date: "2021-05-18"
pubdate: "2021-05-14"
affected_range: "<2.1.4||>=2.2.0,<2.2.3||>=2.3.0,<2.3.3||>=2.4.0,<2.4.2"
fixed_versions:
- "2.5.0"
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: "All versions starting from 2.1.4 before 2.2.0, all versions starting
  from 2.2.3 before 2.3.0, all versions starting from 2.3.3 before 2.4.0, all versions
  starting from 2.4.2"
solution: "Upgrade to version 2.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29561"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "54912c48-185a-4795-83a6-eaf2172d7c6b"
cwe_ids:
- "CWE-1035"
- "CWE-617"
- "CWE-937"
