---
identifier: "CVE-2021-29569"
package_slug: "pypi/tensorflow"
title: "Out-of-bounds Read"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  The implementation of `tf.raw_ops.MaxPoolGradWithArgmax` can cause reads outside
  of bounds of heap allocated data if attacker supplies specially crafted inputs.
  The implementation assumes that the `input_min` and `input_max` tensors have at
  least one element, as it accesses the first element in two arrays. If the tensors
  are empty, `.flat<T>()` is an empty object, backed by an empty array. Hence, accesing
  even the 0th element is a read outside the bounds."
date: "2021-05-20"
pubdate: "2021-05-14"
affected_range: "<2.1.4||>=2.2.0,<2.2.3||>=2.3.0,<2.3.3||>=2.4.0,<2.4.2"
fixed_versions:
- "2.5.0"
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: "All versions starting from 2.1.4 before 2.2.0, all versions starting
  from 2.2.3 before 2.3.0, all versions starting from 2.3.3 before 2.4.0, all versions
  starting from 2.4.2"
solution: "Upgrade to version 2.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29569"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H"
uuid: "f7cfa439-ebaf-403e-8cdb-6176b1e473ea"
cwe_ids:
- "CWE-1035"
- "CWE-125"
- "CWE-937"
