---
identifier: "CVE-2022-23586"
identifiers:
- "CVE-2022-23586"
- "GHSA-43jf-985q-588j"
package_slug: "pypi/tensorflow"
title: "Reachable Assertion"
description: "Tensorflow is an Open Source Machine Learning Framework. A malicious
  user can cause a denial of service by altering a `SavedModel` such that assertions
  in `function.cc` would be falsified and crash the Python interpreter. The fix will
  be included in TensorFlow We will also cherrypick this commit on TensorFlow, TensorFlow,
  and TensorFlow, as these are also affected and still in supported range."
date: "2022-02-10"
pubdate: "2022-02-04"
affected_range: "<=2.5.2||>=2.6.0,<=2.6.2||==2.7.0"
fixed_versions:
- "2.5.3"
- "2.6.3"
- "2.7.1"
affected_versions: "All versions up to 2.5.2, all versions starting from 2.6.0 up
  to 2.6.2, version 2.7.0"
not_impacted: "All versions after 2.5.2 before 2.6.0, all versions after 2.6.2 before
  2.7.0, all versions after 2.7.0"
solution: "Upgrade to versions 2.5.3, 2.6.3, 2.7.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2022-23586"
- "https://github.com/tensorflow/tensorflow/commit/3d89911481ba6ebe8c88c1c0b595412121e6c645"
- "https://github.com/tensorflow/tensorflow/blob/a1320ec1eac186da1d03f033109191f715b2b130/tensorflow/core/framework/function.cc"
- "https://github.com/tensorflow/tensorflow/commit/dcc21c7bc972b10b6fb95c2fb0f4ab5a59680ec2"
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-43jf-985q-588j"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "85df97aa-1939-4de0-8493-d581f6dc0114"
cwe_ids:
- "CWE-1035"
- "CWE-617"
- "CWE-937"
