---
identifier: "CVE-2019-6446"
identifiers:
- "CVE-2019-6446"
- "GHSA-9fq2-x9r6-wfmf"
package_slug: "pypi/numpy"
title: "Numpy Deserialization of Untrusted Data"
description: "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier.
  It uses the pickle Python module unsafely, which allows remote attackers to execute
  arbitrary code via a crafted serialized object, as demonstrated by a numpy.load
  call. NOTE: third parties dispute this issue because it is  a behavior that might
  have legitimate applications in (for example)  loading serialized Python object
  arrays from trusted and authenticated  sources."
date: "2024-10-08"
pubdate: "2022-05-24"
affected_range: "<=1.16.0"
fixed_versions: []
affected_versions: "All versions up to 1.16.0"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
- "https://github.com/advisories/GHSA-9fq2-x9r6-wfmf"
- "https://github.com/numpy/numpy/issues/12759"
- "https://github.com/numpy/numpy/pull/12889"
- "https://access.redhat.com/errata/RHSA-2019:3335"
- "https://access.redhat.com/errata/RHSA-2019:3704"
- "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
- "https://github.com/numpy/numpy"
- "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2019-108.yaml"
- "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
- "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "b8804275-0868-45f4-9ab6-bfd68ad34e00"
cwe_ids:
- "CWE-502"
- "CWE-937"
- "CWE-1035"
